#!/usr/bin/env php
<?php

/**
 * ------------------------------------------------------------
 * Lucy CLI: Lightpack PHP CLI Assistant.
 * ------------------------------------------------------------
 */

require __DIR__ . '/bootstrap/console.php';